export const ASSET_TYPES={house:"Vivienda",vehicle:"Vehículo",bankAccount:"Cuenta bancaria",investment:"Inversión",cash:"Efectivo",other:"Otros"};
export const DEBT_TYPES={mortgage:"Hipoteca",personalLoan:"Préstamo personal",vehicleLoan:"Préstamo vehículo",credit:"Crédito",deferredPurchase:"Compra aplazada",other:"Otros"};
export const MOVEMENT_TYPES={expense:"Gasto",income:"Ingreso",transfer:"Transferencia",investment:"Inversión",debtPayment:"Pago de deuda",refund:"Reembolso"};
export const METRICS={netWorth:"Patrimonio neto",totalAssets:"Activos",totalDebt:"Deuda total",nonMortgageDebt:"Deuda no hipotecaria",liquidity:"Liquidez",investments:"Inversiones",securityFund:"Fondo de seguridad",securityMonths:"Meses de seguridad",monthlySavings:"Ahorro mensual"};
const sum=values=>values.reduce((total,value)=>total+(Number(value)||0),0);
export const periodFromDate=date=>String(date||"").slice(0,7);
export const movementsForPeriod=(movements,period)=>movements.filter(item=>periodFromDate(item.date)===period);
export function calculateMonthlyIncome(movements,period){return sum(movementsForPeriod(movements,period).filter(x=>x.type==="income").map(x=>x.amount));}
export function calculateMonthlyExpenses(movements,period){return sum(movementsForPeriod(movements,period).filter(x=>x.type==="expense").map(x=>x.amount))-sum(movementsForPeriod(movements,period).filter(x=>x.type==="refund").map(x=>x.amount));}
export function calculateMonthlyCategoryTotals(movements,period){return movementsForPeriod(movements,period).filter(x=>x.type==="expense").reduce((totals,x)=>{totals[x.category||"Otros"]=(totals[x.category||"Otros"]||0)+x.amount;return totals;},{});}
export function calculateMonthlyBalance(movements,period){const items=movementsForPeriod(movements,period);return calculateMonthlyIncome(items,period)+sum(items.filter(x=>x.type==="refund").map(x=>x.amount))-sum(items.filter(x=>x.type==="expense").map(x=>x.amount));}
export function calculateSavings(movements,period){const items=movementsForPeriod(movements,period);return calculateMonthlyBalance(items,period)-sum(items.filter(x=>x.type==="investment").map(x=>x.amount))-sum(items.filter(x=>x.type==="debtPayment").map(x=>x.amount));}
export function calculateSavingsRate(movements,period){const income=calculateMonthlyIncome(movements,period);return income>0?calculateSavings(movements,period)/income:0;}
export function calculateMonthSummary(movements,period){const items=movementsForPeriod(movements,period),income=calculateMonthlyIncome(items,period),expenses=calculateMonthlyExpenses(items,period),investments=sum(items.filter(x=>x.type==="investment").map(x=>x.amount)),debtPayments=sum(items.filter(x=>x.type==="debtPayment").map(x=>x.amount)),refunds=sum(items.filter(x=>x.type==="refund").map(x=>x.amount)),transfers=sum(items.filter(x=>x.type==="transfer").map(x=>x.amount)),balance=income+refunds-sum(items.filter(x=>x.type==="expense").map(x=>x.amount)),savings=balance-investments-debtPayments;return{period,count:items.length,income,expenses:Math.max(0,expenses),refunds,investments,debtPayments,transfers,balance,savings,savingsRate:income>0?savings/income:0,categoryTotals:calculateMonthlyCategoryTotals(items,period)};}
export function calculateSecurityFund(transactions,untilDate="9999-12-31"){return sum(transactions.filter(x=>x.date<=untilDate).map(x=>x.type==="deposit"?x.amount:-x.amount));}
export function calculateSecurityFundMonth(transactions,period){return sum(transactions.filter(x=>periodFromDate(x.date)===period).map(x=>x.type==="deposit"?x.amount:-x.amount));}
export function calculateNetWorth(current){return sum(current.assets.map(x=>x.value))-sum(current.debts.map(x=>x.outstandingBalance));}
export function calculateLiquidity(current){return sum(current.assets.filter(x=>["bankAccount","cash"].includes(x.type)).map(x=>x.value));}
export function calculateDebt(current){const totalDebt=sum(current.debts.map(x=>x.outstandingBalance)),mortgageDebt=sum(current.debts.filter(x=>x.type==="mortgage").map(x=>x.outstandingBalance));return{totalDebt,mortgageDebt,nonMortgageDebt:totalDebt-mortgageDebt,monthlyDebtPayments:sum(current.debts.map(x=>x.monthlyPayment))};}
export function calculate(current,securityFundTransactions=[]){const totalAssets=sum(current.assets.map(x=>x.value)),debt=calculateDebt(current),liquidity=calculateLiquidity(current),investments=sum(current.assets.filter(x=>x.type==="investment").map(x=>x.value)),flow=current.cashFlow||{},monthlySavings=(flow.monthlyIncome||0)-(flow.essentialExpenses||0)-debt.monthlyDebtPayments-(flow.variableExpenses||0)-(flow.monthlyInvestment||0),essentialOutflow=(flow.essentialExpenses||0)+debt.monthlyDebtPayments,securityFund=calculateSecurityFund(securityFundTransactions),securityMonths=essentialOutflow>0?securityFund/essentialOutflow:null;return{totalAssets,...debt,liquidity,investments,netWorth:totalAssets-debt.totalDebt,monthlyIncome:flow.monthlyIncome||0,monthlySavings,savingsRate:flow.monthlyIncome>0?monthlySavings/flow.monthlyIncome:0,essentialOutflow,securityFund,securityMonths};}
export function health(metrics,rules){if(metrics.securityMonths===null)return{key:"unknown",label:"SIN DATOS"};if(metrics.securityMonths<rules.fragileMaxMonths)return{key:"fragile",label:"🔴 FRÁGIL"};if(metrics.securityMonths>=rules.stableMinMonths)return{key:"stable",label:"🟢 ESTABLE"};return{key:"control",label:"🟠 CONTROL"};}
export function createSnapshot(current,securityFundTransactions=[]){const metrics=calculate(current,securityFundTransactions);return{id:crypto.randomUUID(),snapshotDate:current.asOfDate,createdAt:new Date().toISOString(),assets:structuredClone(current.assets),debts:structuredClone(current.debts),cashFlow:structuredClone(current.cashFlow),metrics:structuredClone(metrics)};}
export function evolutionSeries(snapshots,metric,granularity="month",securityFundTransactions=[]){const sorted=[...snapshots].sort((a,b)=>a.snapshotDate.localeCompare(b.snapshotDate)),groups=new Map();for(const snapshot of sorted){const key=granularity==="day"?snapshot.snapshotDate:granularity==="year"?snapshot.snapshotDate.slice(0,4):snapshot.snapshotDate.slice(0,7);groups.set(key,snapshot);}return[...groups.values()].map(snapshot=>{const base=calculate({assets:snapshot.assets,debts:snapshot.debts,cashFlow:snapshot.cashFlow},securityFundTransactions.filter(x=>x.date<=snapshot.snapshotDate));return{date:snapshot.snapshotDate,value:snapshot.metrics?.[metric]??base[metric]??0};});}
